import tkinter
ventana = tkinter.Tk()
ventana.geometry ("500x500")
#etiquetas
bienvenido = tkinter.Label(ventana, text ="BIENVENIDO",font = ("Exotc350 Bd BT",25))
bienvenido.grid(row=1, column=3)
nombre= tkinter.Label(ventana, text ="Nombre",font = ("Exotc350 Bd BT",15))
#los entry son los botones
cajanombre=tkinter.Entry(ventana)
nombre.grid(row=2, column=2)
cajanombre.grid(row=2, column=3)
apellido= tkinter.Label(ventana, text ="Apellido",font = ("Exotc350 Bd BT",15))
cajaapellido=tkinter.Entry(ventana)
apellido.grid(row=3, column=2)
cajaapellido.grid(row=3, column=3)
dia= tkinter.Label(ventana, text ="Día",font = ("Exotc350 Bd BT",15))
cajadia=tkinter.Entry(ventana)
dia.grid(row=4, column=2)
cajadia.grid(row=4, column=3)
mes= tkinter.Label(ventana, text ="Mes",font = ("Exotc350 Bd BT",15))
cajames=tkinter.Entry(ventana)
mes.grid(row=5, column=2)
cajames.grid(row=5, column=3)
Año= tkinter.Label(ventana, text ="Año",font = ("Exotc350 Bd BT",15))
cajaaño=tkinter.Entry(ventana)
Año.grid(row=5, column=2)
cajaaño.grid(row=5, column=3)
#botones
funcion1= tkinter.Button (ventana, text = "Funcion1", padx= 15, pady= 10,font=("Exotc350 Bd BT",15))
funcion2= tkinter.Button (ventana, text = "Funcion2", padx= 15, pady= 10,font=("Exotc350 Bd BT",15))
funcion3= tkinter.Button (ventana, text = "Funcion3", padx= 15, pady= 10,font=("Exotc350 Bd BT",15))
funcion4= tkinter.Button (ventana, text = "Funcion4", padx= 15, pady= 10,font=("Exotc350 Bd BT",15))
Funcion5= tkinter.Button (ventana, text = "Funcion5", padx= 15, pady= 10,font=("Exotc350 Bd BT",15))
funcion1.grid(row=7, column=1)
funcion2.grid(row=7, column=2)
funcion3.grid(row=7, column=3)
funcion4.grid(row=7, column=4)
Funcion5.grid(row=7, column=5)
resultado= tkinter.Label(ventana,text="k",font = ("Exotc350 Bd BT",20))
resultado.grid(row=8, column=3)

ventana.mainloop()